"""
  Project       : Spectometer client
  Author        : Borshch Vladislav
  Contacts      : borchsh.vn@gmail.com
  Workfile      : api_param.py
  Description   : Bunch of common parameters for client
"""

# DAQ constants
pBIT_PER_WORD = 24
pBYTE_PER_WORD = int(pBIT_PER_WORD/8)
# Main spectrum table
pTABLE_SIZE = 1024
pTABLE_SIZE_BIT = int(pTABLE_SIZE*pBIT_PER_WORD)
pTABLE_SIZE_BYTE = int(pTABLE_SIZE_BIT / 8)
## Intergation areas
pAREAS_SIZE = 3
pAREA_SIZE_BIT = int(pAREAS_SIZE*pBIT_PER_WORD)
pAREA_SIZE_BYTE = int(pAREA_SIZE_BIT / 8)
# DAQ timeouts, sec
pUART_TIMEOUT = 3
pETH_TIMEOUT = 2
pTIMEOUT = 1

# Server commands
MSG_SIZE = 3
RPL_SIZE_MAX = 2
VAL_SIZE = 4
ADC_NUMBER = 4
SHIELD_SENSORS_NUM = 1

SPECTRUM_NUM = pTABLE_SIZE + pAREAS_SIZE
SPECTRUM_SIZE = SPECTRUM_NUM * VAL_SIZE
INFO_NUM = (4 + 1 + 1)
INFO_SIZE = INFO_NUM*VAL_SIZE
DAQ_SAMPLES_NUM = SPECTRUM_NUM + INFO_NUM
BUF_SIZE = VAL_SIZE*DAQ_SAMPLES_NUM
CMD_SIZE = 8
CMD_ADDR_WR  = 0x00
CMD_ADDR_RD  = 0x01
CMD_RUN_DAQ  = 0x02
CMD_STOP_DAQ = 0x03
CMD_READ_TMP = 0x04
CMD_READ_ADC = 0x05
CMD_READ_DAC = 0x06
CMD_WRITE_DAC    = 0x07
CMD_WRITE_EEPROM = 0x08
CMD_GET_UPTIME   = 0x09
CMD_DUMP_WAVE    = 0x0A
CMD_GET_DAEMON_VERSION = 0x10000000

SCPI_ADDR_RD = "SP:READ:ADDR? "
SCPI_ADDR_WR = 'SP:WRITE:ADDR '
SCPI_WRITE_EEPROM = 'SP:WRITE:EEPROMDAC '
SCPI_WRITE_DAC= 'SP:WRITE:DAC '
SCPI_GET_UPTIME = 'SP:UPTIME?'
SCPI_GET_DAEMON_VERSION = 'SP:VER:DRV?'
SCPI_READ_ADC = 'SP:READ:ADC? '
SCPI_READ_TMP = 'SP:TEMP? '
SCPI_RUN_DAQ  = 'SPEC?'

SCPI_WAVE_DUMP = 'WAVE? ' 



